# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7f89dfc5279d00990b193befe5845a718458403bcab724f2bc08645179ce2bb9c7ed8266cc7885eb012d8100f4bc9fc370d583c5c2cc4b84558b66c5b7fa184

test:
  secret_key_base: c663d8c3dabe4ec4f64393b74a03be128cbfcb2b9ac58821de49328c4eb93098e1836b0a325dcb213c4f11da20306a3c825143c2473f49af58096be7cd8aa2ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
